---
- name: generate redis config
  copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: root
    group: wheel
    mode: 0644
  notify: restart redis

- name: enable redis
  service:
    name: redis
    enabled: true
    state: started

- name: flush_handlers
  meta: flush_handlers
