---
- name: get excision UID
  command: id -u excision
  register: excisionUID
  changed_when: false

- name: enable dovecot
  service:
    name: dovecot
    enabled: true

- name: create dovecot directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.user | default('excision') }}"
    group: "{{ item.group | default('excision') }}"
    mode: "{{ item.mode | default('0770') }}"
    state: directory
  with_items: "{{ dovecot_directories }}"
  notify: restart dovecot

- name: copy dovecot sieve files
  copy:
    src: "{{ item.name }}"
    dest: "{{ item.path | default('/usr/local/lib/dovecot/sieve') }}/{{ item.name }}"
    owner: "{{ item.user | default('excision') }}"
    group: "{{ item.group | default('excision') }}"
    mode: "{{ item.mode | default('0770') }}"
    force: true
  with_items: "{{ dovecot_sieve_files }}"
  notify: restart dovecot

- name: copy dovecot template files
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.path | default('/etc/dovecot/conf.d') }}/{{ item.name }}"
    owner: "{{ item.user | default('root') }}"
    group: "{{ item.group | default('wheel') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ dovecot_templates }}"
  notify: restart dovecot

- name: copy dovecot config files
  copy:
    src: "{{ item.name }}"
    dest: "{{ item.path | default('/etc/dovecot/conf.d') }}/{{ item.name }}"
    owner: "{{ item.user | default('root') }}"
    group: "{{ item.group | default('wheel') }}"
    mode: "{{ item.mode | default('0644') }}"
    force: true
  with_items: "{{ dovecot_config_files }}"
  notify: restart dovecot

- name: symlink dovecot ldap config
  file:
    src: "dovecot-ldap.conf.ext"
    dest: "/etc/dovecot/dovecot-ldap-{{ item.name }}.conf.ext"
    state: link
    force: true
  with_items:
    - {name: "passdb"}
    - {name: "userdb"}
  notify: restart dovecot

- name: flush_handlers
  meta: flush_handlers
