#!/bin/sh

dkim_home="/etc/excision/dkim"
ssl_home="/etc/excision/ssl"
nsd_home="/etc/excision/nsd"
user_home="/etc/excision/users"
spam_home="/etc/excision/spam"

wks_home="/var/lib/gnupg/wks"

emhome="/var/excision-home"
empasswd="/var/excision-passwd"
emmails="/var/excision"
emconfig="/etc/excision"

emscripts="/usr/local/lib/excision"
emhelpers="/usr/local/lib/excision/helpers"

empasswdfile="$empasswd/.ssh/authorized_keys"
empasswdtempfile="$user_home/authorized_keys"

vfix="$emhelpers/verbose-fix"
