#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

if [ $# -lt 1 ]; then
	echo "Error: AnsiMail called with no arguments"
	exit 2
fi

command=$1
shift

case "$command" in
	"ensure-dkim")
		/bin/sh /usr/local/lib/ansimail/ensure-dkim "$@";;
	"renew-certs")
		/bin/sh /usr/local/lib/ansimail/renew-certs "$@";;
	"show-stats")
		/bin/sh /usr/local/lib/ansimail/show-stats "$@";;
	"add-alias")
		/bin/sh /usr/local/lib/ansimail/add-alias "$@";;
	"add-user")
		/bin/sh /usr/local/lib/ansimail/add-user "$@";;
	"change-passwd")
		/bin/sh /usr/local/lib/ansimail/change-passwd "$@";;
	"daily-report")
		/bin/sh /usr/local/lib/ansimail/daily-report "$@";;
	"userdb-check")
		/bin/sh /usr/local/lib/ansimail/userdb-check "$@";;
	"fix-perms")
		/bin/sh /usr/local/lib/ansimail/fix-perms "$@";;
	"virtual-regen")
		/bin/sh /usr/local/lib/ansimail/virtual-regen "$@";;
	"ensure-gpg")
		/bin/sh /usr/local/lib/ansimail/ensure-gpg "$@";;
	"ensure-zone")
		/bin/sh /usr/local/lib/ansimail/ensure-zone "$@";;
	*)
		echo "Unknown argument"
		exit 3;;
esac
