#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

command=$1
shift

case "$command" in
	"ensure-dkim")
		/bin/sh /usr/local/lib/ansimail/ensure-dkim "$@";;
	"renew-certs")
		/bin/sh /usr/local/lib/ansimail/renew-certs "$@";;
	"show-stats")
		/bin/sh /usr/local/lib/ansimail/show-stats "$@";;
	"add-alias")
		/bin/sh /usr/local/lib/ansimail/add-alias "$@";;
	"add-user")
		/bin/sh /usr/local/lib/ansimail/add-user "$@";;
	"change-passwd")
		/bin/sh /usr/local/lib/ansimail/change-passwd "$@";;
	"daily-report")
		/bin/sh /usr/local/lib/ansimail/daily-report "$@";;
	"userdb-check")
		/bin/sh /usr/local/lib/ansimail/userdb-check "$@";;
	"fix-perms")
		/bin/sh /usr/local/lib/ansimail/fix-perms "$@";;
	"virtual-regen")
		/bin/sh /usr/local/lib/ansimail/virtual-regen "$@";;
	"ensure-gpg")
		/bin/sh /usr/local/lib/ansimail/ensure-gpg "$@";;
	"ensure-zone")
		/bin/sh /usr/local/lib/ansimail/ensure-zone "$@";;
	"whitelist-bigmailer")
		/bin/sh /usr/local/lib/ansimail/whitelist-bigmailer "$@";;
	"whitelist-friend")
		/bin/sh /usr/local/lib/ansimail/whitelist-friend "$@";;
	*)
		echo "ansimail ensure-dkim"
		echo "ansimail renew-certs"
		echo "ansimail show-stats"
		echo "ansimail add-alias <alias> <user>"
		echo "ansimail add-user <user>"
		echo "ansimail change-passwd <user>"
		echo "ansimail daily-report"
		echo "ansimail userdb-check"
		echo "ansimail fix-perms"
		echo "ansimail ensure-gpg"
		echo "ansimail ensure-zone"
		echo "ansimail whitelist-bigmailer <domain>"
		echo "ansimail whitelist-friend <ip>"
		exit 3;;
esac
