#!/bin/sh

wks_home="/var/lib/gnupg/wks"

gpg-wks-server --list-domains

while read -r domain; do

	echo "wks@$domain" > "$wks_home/$domain/submission-address"

	gpg -K "wks@$domain"

	if [ $? -ne 0 ]; then
		gpg --batch --passphrase "" --quick-gen-key "wks@$domain"
	fi

	fingerprint=$(gpg -K "wks@$domain" | sed "2q;d")
	fingerprint=${fingerprint##*( )}

	gpg-wks-server --install-key "$fingerprint" "wks@$domain"
done < /etc/mail/vdomains

