#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

HELP=$(cat <<-END
Available options are:
    ensure-dkim
        Regenerate DKIM txt record and store it in /etc/ansimail/dkim

    renew-certs
        Renews certificates using acme-client

    show-stats
        Show statistics of email services

    add-alias "alias@domain.tld" "user@domain.tld"
        Add alias for user

    add-user "user@domain.tld"
        Add new user "user@domain.tld"

    change-passdw "user@domain.tld"
        Change the existing password for "user@domain.tld"

    daily-report
        Daily maintenance for AnsiMail

    userdb-check
        Check consistency of user database

    fix-perms
        Fix permissions for AnsiMail related folders

    virtual-regen
        Assuming that userdb-check has returned correct, recreate the smtpd tables
        and reload all services depending on the passwor database. 
        MUST RUN "userdb-check" MANUALLY

    ensure-gpg
        Do the bare minimum gpg fixing so that newer keys can be published using WKS

    ensure-zone
        Creates an example zone file backup in /var/nsd/zones/master/domain.zone.tmp
        DOES NOT DEPEND ON OR AFFECT CURRENT NSD CONFIG

    whitelist-bigmailer "domain"
        Finds and whitelists all ips associated with "domain", for spamd

    whitelist-friend "ip"
        Whitelists "ip" for spamd
END
)


if [ $# -lt 1 ]; then
	echo "$HELP"
	exit 2
fi

command=$1
shift

case "$command" in
	"ensure-dkim")
		/bin/sh /usr/local/lib/ansimail/ensure-dkim "$@";;
	"renew-certs")
		/bin/sh /usr/local/lib/ansimail/renew-certs "$@";;
	"show-stats")
		/bin/sh /usr/local/lib/ansimail/show-stats "$@";;
	"add-alias")
		/bin/sh /usr/local/lib/ansimail/add-alias "$@";;
	"add-user")
		/bin/sh /usr/local/lib/ansimail/add-user "$@";;
	"change-passwd")
		/bin/sh /usr/local/lib/ansimail/change-passwd "$@";;
	"daily-report")
		/bin/sh /usr/local/lib/ansimail/daily-report "$@";;
	"userdb-check")
		/bin/sh /usr/local/lib/ansimail/userdb-check "$@";;
	"fix-perms")
		/bin/sh /usr/local/lib/ansimail/fix-perms "$@";;
	"virtual-regen")
		/bin/sh /usr/local/lib/ansimail/virtual-regen "$@";;
	"ensure-gpg")
		/bin/sh /usr/local/lib/ansimail/ensure-gpg "$@";;
	"ensure-zone")
		/bin/sh /usr/local/lib/ansimail/ensure-zone "$@";;
	"whitelist-bigmailer")
		/bin/sh /usr/local/lib/ansimail/whitelist-bigmailer "$@";;
	"whitelist-friend")
		/bin/sh /usr/local/lib/ansimail/whitelist-friend "$@";;
	*)
		echo "$HELP"
		exit 3;;
esac
