---
- name: create acme config
  template:
    src: acme-client.conf.j2
    dest: /etc/excision/ssl/acme-client.conf
    owner: root
    group: wheel
    mode: "0644"

- name: create acme certs
  command: excision renew-certs
  register: renew_certs
  failed_when: renew_certs.rc == 1
  changed_when: renew_certs.rc == 0

- name: create symlinks for certificates
  file:
    src: "/etc/excision/ssl/{{ item[0].prefix | default('') }}{{ item[1].name }}{{ item[0].suffix }}"
    dest: "/etc/ssl/{{ item[0].prefix | default('') }}{{ item[1].name }}{{ item[0].suffix }}"
    owner: root
    group: wheel
    state: link
  with_nested:
    - "{{ padding }}"
    - "{{ domains }}"
