#!/bin/sh

# This script assumes that you are working with 
# a clean database that has been verified with userdb-check
# The behaviour is undefined on random unstable databases
# It may mutate your cat and make your kombucha lose its fizzzzzzz

. /usr/local/lib/ansimail/helpers/variables

if [ "$#" -ne 2 ]; then
	echo "Incorrect number of arguments to add-user: user@domain [0/1 (for adding ssh-key)]"
	exit 255
fi

user="$1"

user_status=$(sh "$amscripts/helpers/check-user" "$user")

case $user_status in
	1)
		echo "User $user already exists as real user"
		exit 1
		;;
	2)
		echo "User $user already exists as an alias"
		exit 2
		;;
	*)
		echo "User $user currently not in system, proceeding to add them"
		;;
esac

printf "Password: "
read -r password
printf "\n"

# now the second part where we allow users to change their passwords
# by letting them ssh to ansimail-passwd user

# if we don't want the funtionality to change password
# we can skip this part
if [ "$2" -eq 1 ]; then
	# we run the set-user-key
	sh "$amscripts/add-user-key" "$user"
fi

touch "$user_home/user-data/$user"
chmod 700 "$user_home/user-data/$user"

password=$(echo "$password" | smtpctl encrypt)

echo "$user:$password::::::::" >> "$user_home/passwd"

