#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

. /usr/local/lib/ansimail/helpers/variables

user=$1

printf "Password: "
read -r password
printf "\n"

password=$(echo "$password" | smtpctl encrypt)
echo "$password"

sed -i "/$user/d" "$user_home/passwd"

echo "$user:$password::::::::" >> "$user_home/passwd"

cp "$user_home/passwd" /etc/mail/passwd
chmod 440 /etc/mail/passwd
chown _smtpd:_dovecot /etc/mail/passwd

