#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

printf "##### Pending syspatches\n"
syspatch -c

printf "\n##### Pending package upgrades\n"
pkg_add -su

printf "\n##### Pending acme certificates\n"
/usr/local/bin/ansimail renew-certs

printf "\n##### Pending user database checks\n"
/usr/local/bin/ansimail userdb-check

printf "\n##### Fixing big mailers list\n"
smtpctl spf walk < /etc/ansimail/spam/bigmailer-names | pfctl -t bigmailers -T add -f -
pfctl -t bigmailers -T show > /etc/ansimail/spam/bigmailers

printf "\n##### Cleaning pending gpg requests\n"
find /var/www/openpgpkey/*/pending/ -type f -delete

/usr/local/bin/ansimail show-stats
