#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

printf "\n##### Pending syspatches\n"
syspatch -c

printf "\n##### Pending package upgrades\n"
pkg_add -su

printf "\n##### Pending acme certificates\n"
/usr/local/bin/ansimail renew-certs

printf"\n##### Pending user database checks\n"
/usr/local/bin/ansimail userdb-check

printf "\n##### AnsiMail stats\n"
/usr/local/bin/ansimail show-stats
