#!/bin/sh

### Deletes a virtual alias $1

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

. /usr/local/lib/ansimail/helpers/variables

alias="$1"

sed -i "/$alias/d" "$user_home/user-data/$user" \
	| tee "$user_home/user-data/$user" > /dev/null
