#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

# This script assumes that you are working with 
# a clean database that has been verified with userdb-check
# The behaviour is undefined on random unstable databases
# It may mutate your cat and make your kombucha lose its fizzzzzzz

. /usr/local/lib/ansimail/helpers/variables

user="$1"

sed -i "/$user/d" "$user_home/passwd" \
	| tee "$user_home/passwd" > /dev/null
