#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

. /usr/local/lib/ansimail/helpers/variables

wks_home="/var/lib/gnupg/wks"

mkdir -p "$wks_home"
chown ansimail:ansimail "$wks_home"
chmod 2750 "$wks_home"

mkdir -p /var/www/openpgpkey
[ -f "$spam_home/submission-address" ] && rm "$spam_home/submission-address"

while read -r domain; do
	mkdir -p "/var/www/openpgpkey/$domain"
	ln -sfh "/var/www/openpgpkey/$domain" "$wks_home/$domain"
	echo "wks@$domain" >> "$spam_home/submission-address"
done < /etc/mail/vdomains

chown -R ansimail:ansimail /var/www/openpgpkey

su -l ansimail -c "sh /var/ansimail-home/ansimail-wks-init"
