#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

. /usr/local/lib/ansimail/helpers/variables

domain=$( head -n 1 /etc/mail/vdomains )
key_file="$dkim_home/private/ansimail.$domain.key"
pub_file="$dkim_home/ansimail.$domain.pub"
txt_file="$dkim_home/ansimail.$domain.txt"

echo "##### Generating/Checking DKIM certificates for domain: $domain"

printf "\n\n### Making sure private key file exists\n"
if [ ! -e "$key_file" ]; then 
	openssl genrsa -out "$key_file" 2048
fi

openssl rsa -in "$key_file" -check

if [ $? -ne 0 ]; then
	openssl genrsa -out "$key_file" 2048
fi

printf "\n\n### Making sure public key file exists\n"

openssl rsa -in "$key_file" -pubout -out "$pub_file"

printf "\n\n### Ensuring correct permissions on both files\n"
sh $vfix root _rspamd 640 "$key_file"
sh $vfix root wheel 644 "$pub_file"

printf "\n\n### Creating txt record from public key\n"

txt_begin="ansimail._domainkey	IN	TXT	"

publickey=$(awk 'NR>2 {print last} {last=$0}' ORS='' "$pub_file")
publickey="v=DKIM1;k=rsa;p=$publickey;"
txt_end=$(echo "$publickey" | awk 'BEGIN {ORS=" "}{for (i=1;i<=length($0);i+=255) printf "\042%s\042 ",substr( $0, i, 255 ) } ')

echo "$txt_begin( $txt_end)" | tee "$txt_file"

sh $vfix root wheel 644 "$txt_file"
