#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

printf "\n\n### Fixing permissions of AnsiMail config + script files\n\n"

chown root:wheel /usr/local/lib/ansimail/fix-perms /usr/local/lib/ansimail/helpers/verbose-fix
chmod 600 /usr/local/lib/ansimail/fix-perms /usr/local/lib/ansimail/helpers/verbose-fix

# Now that bootstrapping is done

. /usr/local/lib/ansimail/helpers/variables

find "$amscripts" -type d -exec sh "$vfix" root wheel 700 {} \;
find "$amscripts" -type f -exec sh "$vfix" root wheel 600 {} \;

find "$amconfig" -path "$user_home" -prune -o -path "$ssl_home/private" -prune \
	-o -path "$dkim_home/private" -prune -o -type d \
	-exec sh "$vfix" root wheel 755 {} \;
find "$amconfig" -path "$user_home" -prune -o -path "$ssl_home/private" -prune \
	-o -path "$dkim_home/private" -prune -o -type f \
	-exec sh "$vfix" root wheel 644 {} \;

find "$user_home" -type d -exec sh "$vfix" root wheel 700 {} \;
find "$user_home" -type f -exec sh "$vfix" root wheel 600 {} \;

find "$ssl_home/private" -type d -exec sh "$vfix" root wheel 750 {} \;
find "$ssl_home/private" -type f -exec sh "$vfix" root wheel 400 {} \;

find "$dkim_home/private" -type d -exec sh "$vfix" root _rspamd 750 {} \;
find "$dkim_home/private" -type f -exec sh "$vfix" root _rspamd 640 {} \;


printf "\n\n### Fixing permissions of base install\n\n"

printf "\n\n### Fixing permissions of nsd files\n\n"

printf "\n\n### Fixing permissions of OpenSMTPD files\n\n"

printf "\n\n### Fixing permissions of httpd + acme files\n\n"

printf "\n\n### Fixing permissions of OpenPGP WKS/WKD files\n\n"

printf "\n\n### Fixing permissions of Dovecot files\n\n"

find /etc/dovecot -type d -exec sh "$vfix" root wheel 755 {} \;
find /etc/dovecot -type f -exec sh "$vfix" root wheel 644 {} \;

printf "\n\n### Fixing permissions of Clamd files\n\n"

sh "$vfix" root wheel 644 /etc/freshclam.conf
sh "$vfix" root wheel 644 /etc/clamd.conf

printf "\n\n### Fixing permissions of Rspamd files\n\n"

find /etc/rspamd -type d -exec sh "$vfix" root wheel 755 {} \;
find /etc/rspamd -type f -exec sh "$vfix" root wheel 644 {} \;
