#!/bin/sh

if [ $(id -u) -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

domain=$1

. /usr/local/lib/ansimail/helpers/variables

echo "### Renewing acme certificates"
acme-client -v -f $ssl_home/acme-client.conf $domain && {
	echo "\n### Reloading services"
	rcctl reload httpd dovecot
	rcctl restart smtpd
}
