#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

. /usr/local/lib/ansimail/helpers/variables

echo "### Renewing acme certificates"
while read -r domain; do
	acme-client -v -f "$ssl_home/acme-client.conf" "openpgpkey.$domain" 
done < /etc/mail/vdomains

echo "\n### Reloading services"
rcctl reload httpd dovecot
rcctl restart smtpd spamd

