#!/bin/sh

# This script assumes that you are working with 
# a clean database that has been verified with userdb-check
# The behaviour is undefined on random unstable databases
# It may mutate your cat and make your kombucha lose its fizzzzzzz

. /usr/local/lib/ansimail/helpers/variables

if [ "$#" -ne 1 ];
	echo "Incorrect number of arguments to set-user-key: user@domain"
	exit 255
fi

user="$1"

user_status=$(sh "$amscripts/helpers/check-user" "$user")

case $user_status in
	1)
		echo "User $user exists as real user, adding their key..."
		;;
	2)
		echo "Error: User $user exists as an alias"
		exit 1
		;;
	*)
		echo "Error: User $user currently not in system"
		exit 2
		;;
esac

printf "ssh-key: "
read -r ssh_key
printf "\n"

# first do a sanity check on the public key
echo "$ssh_key" | ssh-keygen -l -f -

if [ "$?" -ne 0 ]; then
	echo "Error: not a valid public key file"
	exit 3
fi

