#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

printf "\n### SMTPD statistics\n"
smtpctl show stats

printf "\n### Rspamd statistics\n"
/usr/local/bin/rspamc stat

printf "\n### Dovecot statistics\n"
su -l ansimail -c "/usr/local/bin/doveadm -f pager quota get -A | tr -d '\f'"
