#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

printf "\n### SMTPD statistics"
smtpctl show stats

printf "\n### Rspamd statistics"
rspamc stat

printf "\n### Dovecot statistics"
echo "TODO: get doveadm statistics"
