#!/bin/sh

# Checks the consistency of user database and password database

. /usr/local/lib/ansimail/helpers/variables

virtuals="$user_home/virtual"
revirt="$user_home/revirt"
bak=$(date +%Y%d%m%H%M)

if [ -e "$virtuals" ]; then
	mv "$virtuals" "$virtuals.$bak"
fi
if [ -e "$reivrt" ]; then
	mv "$revirt" "$revirt.$bak"
fi

touch "$virtuals" "$revirt"

# Now check that every alias is only an alias
# (this also ensures that every use is only a user, due to bipartite-ness)
for user_file in "$user_home/user-data/"*; do
	username=$( basename "$user_file" )
	printf "\n%s\t\t\t\tansimail" "$username" >> "$virtuals"
	printf "%s\t\t\t\t%s" "$username" "$username" >> "$revirt"
	while IFS= read -r alias; do
		printf "%s\t\t\t\t%s" "$alias" "$username" >> "$virtuals"
		printf ",%s", "$alias" >> $revirt
	done < "$user_home/user-data/$username"
	printf "\n" >> "$revirt"
done

cp "$virtuals" /etc/mail/virtual
cp "$revirt" /etc/mail/revirt
chmod 640 /etc/mail/virtual /etc/mail/revirt
chown root:_smtpd /etc/mail/virtual /etc/mail/revirt
cp "$user_home/passwd" /etc/mail/passwd
chmod 440 /etc/mail/passwd
chown _smtpd:_dovecot /etc/mail/passwd

# Restart services
/usr/sbin/rcctl restart smtpd dovecot
