#!/bin/sh

. /usr/local/lib/ansimail/helpers/variables

if [ "$#" -eq 0 ]; then
	echo "Error: no big mailer domain specified"
	exit 255
fi

domain="$1"
bigmailers="$spam_home/bigmailer-names"

touch "$bigmailers"

if grep -q "$domain" "$bigmailers"; then 
	echo "$domain is already registered as a big mail corp"
	exit 1
else
	echo "$domain" >> "$bigmailers"
	echo "$domain" | smtpctl spf walk | pfctl -t bigmailers -T add -f -
	# also do another backup
	pfctl -t bigmailers -T show > "$spam_home/bigmailers"
fi

