#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
       echo "This can only be run by root"
        exit 1
fi

. /usr/local/lib/ansimail/helpers/variables

ip="$1"
nospamd="$spam_home/nospamd"

touch "$nospamd"

if grep -q "$ip" "$nospamd"; then
	echo "$ip is already bypassing spamd"
	exit 1
else
	echo "$domain" >> "$nospamd"
	pfctl -t nospamd -T replace -f "$nospamd"
fi

