#!/bin/sh

ip="$1"
nospamd="/etc/ansimail/spam/nospamd"

touch "$nospamd"

if grep -q "$ip" "$nospamd"; then
	echo "$ip is already bypassing spamd"
	exit 1
else
	echo "$domain" >> "$nospamd"
	pfctl -t nospamd -T replace -f "$nospamd"
fi

