#!/bin/sh

### Creates a virtual alias $1 and forwards all messages to $2

. /usr/local/lib/excision/helpers/variables

# make sure that we are only getting two inputs
if [ "$#" -ne 2 ]; then
	echo "Incorrect number of arguments to add-alias: alias@domain2 user@domain1"
	exit 255
fi

alias=$1
user=$2

# first we get the status of the current inputs
alias_out=$(sh "$emscripts/helpers/check-user" "$alias")
alias_status=$?
user_out=$(sh "$emscripts/helpers/check-user" "$user")
user_status=$?

# Make sure that user exists
case $user_status in
	0)
		echo "User doesn't exist as a real user"
		exit 1
		;;
	2)
		echo "User is actually an alias to another user: $user_out"
		exit 3
		;;
	1)
		echo "User exists, proceeding to check the alias"
		;;
esac

case $alias_status in
	2)
		echo "Alias already used by a user - $alias_out"
		if [ "$alias_out" = "$user" ]; then
			exit 2;
		fi
		exit 4
		;;
	1)
		echo "Alias is already a real user on the system"
		exit 5
		;;
	*)
		echo "Alias is not currently in use, proceeding to add it"
		;;
esac

echo "$alias" >> "$user_home/user-data/$user"
