#!/bin/sh

# This script assumes that you are working with 
# a clean database that has been verified with userdb-check
# The behaviour is undefined on random unstable databases
# It may mutate your cat and make your kombucha lose its fizzzzzzz

. /usr/local/lib/excision/helpers/variables

if [ "$#" -eq 0 ]; then
	echo "Incorrect number of arguments to add-user: user@domain"
	exit 255
fi

user="$1"

user_out=$(sh "$emscripts/helpers/check-user" "$user")
user_status=$?

case $user_status in
	1)
		echo "User $user already exists as real user"
		exit 2
		;;
	2)
		echo "User $user already exists as an alias for a user - $user_out"
		exit 1
		;;
	*)
		echo "User $user currently not in system, proceeding to add them"
		;;
esac

printf "Password: "
read -r password
printf "\n"

touch "$user_home/user-data/$user"
chmod 700 "$user_home/user-data/$user"

password=$(echo "$password" | smtpctl encrypt)

echo "$user:$password::::::::" >> "$user_home/passwd"
