#!/bin/sh

. /usr/local/lib/excision/helpers/variables

if [ "$#" -ne 1 ]; then
	echo "Incorrect number of arguments to change-passwd: user@domain"
	exit 255
fi

user=$1

/bin/sh "$emscripts/helpers/check-user" "$user" >/dev/null
user_status=$?

case $user_status in
	1)
		echo "User $user exists as real user, continuing..."
		;;
	2)
		echo "Error: user $user exists as an alias"
		exit 1
		;;
	*)
		echo "Error: user $user currently not in system"
		exit 2
		;;
esac

printf "Password: "
read -r password
printf "\n"

password=$(echo "$password" | smtpctl encrypt)
echo "$password"

sed -i "/\<$user\>/d" "$user_home/passwd"

echo "$user:$password::::::::" >> "$user_home/passwd"
