#!/bin/sh

. /usr/local/lib/excision/helpers/variables

# this script creates a zone file for the given
# domain, assuming that the template zone file 
# exists in the /etc/excision/nsd folder

domain="$1"
nsd_restart_=1
if [ "$#" -eq 2 ]; then
	nsd_restart_="$2"
fi

# by default, we don't install it
# up to the admin to make sure that it gets installed 
zone_file_="/var/nsd/zones/master/$domain.zone"
zone_file="$zone_file_".tmp

newserial=$(($(date +%y%m%d%H%M) + 20000000))

sed -e "s/EXCISIONSERIAL/$newserial/g" "$nsd_home/$domain.zone" > "$zone_file"

cat "$dkim_home/excisionRSA.$domain.txt" >> "$zone_file"
cat "$dkim_home/davRSA.$domain.txt" >> "$zone_file"

# if we had an addon file, we also add its contents
# very useful for hosting your other dynamic DNS websites
[ -e "$nsd_home/$domain.zone.addon" ] && cat "$nsd_home/$domain.zone.addon" >> "$zone_file"

printf "\n" >> "$zone_file"

sh "$vfix" root wheel 644 "$zone_file"

if nsd-checkzone "$domain" "$zone_file"; then
	mv "$zone_file" "$zone_file_"
	[ "$nsd_restart_" = 0 ] || rcctl restart nsd
else
	printf %s\\n "error in zone file syntax: $domain - $zone_file"
	exit 1
fi
