---
- name: ensure httpd.conf exists
  file:
    path: /etc/httpd.conf
    state: touch
    owner: root
    group: wheel
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: ensure httpd-extras.conf is included in httpd.conf
  lineinfile:
    path: /etc/httpd.conf
    line: 'include "/etc/httpd-extras.conf"'
    state: present
  notify: restart httpd

- name: generate httpd-extras.conf
  template:
    src: httpd-extras.conf.j2
    dest: /etc/httpd-extras.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart httpd

- name: enable httpd
  service:
    name: httpd
    enabled: true
    state: started

- name: flush_handlers
  meta: flush_handlers
