---
base_packages:
  - "dovecot"
  - "dovecot-pigeonhole"
  - "gnupg"
  - "knot"
  - "opensmtpd-extras"
  - "opensmtpd-filter-rspamd"
  - "opensmtpd-filter-senderscore"
  - "redis"
  - "rspamd--"

base_services:
  - {name: "dovecot"}
  - {name: "httpd"}
  - {name: "redis"}
  - {name: "relayd"}
  - {name: "rspamd"}

base_config_dirs:
  - {name: "/etc/excision/dkim/private", perm: "0755"}
  - {name: "/etc/excision/ssl/private", perm: "0755"}
  - {name: "/etc/excision/nsd", perm: "0755"}
  - {name: "/etc/excision/spam", perm: "0755"}
  - {name: "/etc/excision/users", perm: "0700"}
  - {name: "/etc/excision/users/user-data", perm: "0700"}
