---
- name: install roundcube packages
  openbsd_pkg:
    name: "{{ roundcube_packages }}"
    state: present

- name: create config file for roundcubemail
  template:
    src: config.inc.php.j2
    dest: /var/www/roundcubemail/config/config.inc.php
    owner: root
    group: wheel
    mode: 0644

- name: include roundcube plugins
  include: roundcube_plugins.yml

- name: include roundcue postgresql
  include: roundcube_pgsql.yml

- name: flush_handlers
  meta: flush_handlers
