---
- name: install roundcube packages
  package:
    name: "{{ roundcube_packages }}"
    state: present

- name: create config file for roundcubemail
  template:
    src: config.inc.php.j2
    dest: /var/www/roundcubemail/config/config.inc.php
    owner: root
    group: wheel
    mode: '0644'

- name: include roundcube plugins
  import_tasks: roundcube_plugins.yml

- name: include roundcue mysql
  import_tasks: roundcube_mysql.yml

- name: flush_handlers
  meta: flush_handlers
