---
- name: clone git plugins
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version }}"
    dest: "/var/www/roundcubemail/plugins/{{ item.plugin }}"
    force: true
  with_items: "{{ roundcube_extra_plugins_git }}"

- name: extract archived plugins
  unarchive:
    src: "{{ item.src }}"
    dest: "/var/www/roundcubemail/plugins"
    remote_src: true
    owner: www
    group: www
  with_items: "{{ roundcube_extra_plugins_tgz }}"

- name: create config for plugins
  copy:
    src: "plugin_configs/{{ item | basename }}"
    dest: "/var/www/roundcubemail/plugins/{{ item | basename }}/config.inc.php"
    owner: www
    group: www
    mode: '0644'
  loop: "{{ lookup('fileglob', 'plugin_configs/*', wantlist=true) }}"

- name: own the directories for plugins  # noqa 208
  file:
    path: "/var/www/roundcubemail/plugins"
    state: directory
    owner: www
    group: www
    recurse: true
    modification_time: preserve
    access_time: preserve
