---
- name: clone git plugins
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version }}"
    dest: "/var/www/roundcubemail/plugins/{{ item.plugin }}"
    force: true
  with_items: "{{ roundcube_extra_plugins_git }}"

- name: extract archived plugins
  unarchive:
    src: "https://github.com/mstilkerich/rcmcarddav/releases/download/v4.3.0/carddav-v4.3.0.tar.gz"
    dest: "/var/www/roundcubemail/plugins"
    remote_src: true
    owner: www
    group: www

- name: create config for plugins
  copy:
    src: "plugin_configs/{{ item | basename }}"
    dest: "/var/www/roundcubemail/plugins/{{ item | basename }}/config.inc.php"
    owner: www
    group: www
    mode: '0644'
  loop: "{{ lookup('fileglob', 'plugin_configs/*', wantlist=true) }}"

- name: own the directories for plugins
  file:
    path: "/var/www/roundcubemail/plugins"
    state: directory
    owner: www
    group: www
    recurse: true
    modification_time: preserve
    access_time: preserve
