#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	printf %s\\n "excision can only be run by root"
	exit 1
fi

HELP=$(cat <<-END
usage:  excision add-alias alias@domainA.tldA user@domainB.tldB
        excision add-user user@domain.tld [1]
        excision add-user-key | change-passwd | deleteall-user-keys
                 user@domain.tld
        excision daily-report | ensure-dkim | ensure-gpg | fix-perms |
                 renew-certs | show-stats | userdb-check | virtual-regen
        excision ensure-zone [domain.tld]
        excision whitelist-bigmailer domain.tld
        excision whitelist-friend IP
END
)

if [ $# -lt 1 ]; then
	printf %s\\n "${HELP}"
	exit 2
fi

command="$1"
shift

script_home="/usr/local/lib/excision"

if [ -f "${script_home}/${command}" ] && [ -x "${script_home}/${command}" ]; then
	"${script_home}/${command}" "${@}"
else
	printf %s\\n "${HELP}"
	exit 3
fi
