#!/bin/sh

# Output / return code:  ""  / 0 -> Doesn't exist as either alias or user
#                        ""  / 1 -> Exists as a user
#                       user / 2 -> Exists as alias for another user

. /usr/local/lib/excision/helpers/variables

username="$1"

if [ -e "$user_home/user-data/$username" ]; then
 	exit 1;
fi

for user in "$user_home/user-data/"*; do
	[ -e "$user" ] || continue
	if grep -q "^$username\$" "$user"; then
		echo "$(basename $user)"
		exit 2
	fi
done
