#!/bin/sh

# Output: 0 -> Valid username
#         1 -> Invalid username

# error code: 0 -> username valid + proper syntax
#             1 -> username improper syntax (contains more than one @)
#             2 -> username not valid due to incorrect domain

. /usr/local/lib/excision/helpers/variables

username="$1"
set -- $(echo $username | sed -e "s/@/ /g")

if [ $# -gt 2 ]; then
	echo 1
	exit 1
elif grep -q "^$2$" "/etc/mail/vdomains"; then
	echo 0
	exit 0
else
	echo 1
	exit 2
fi
