- name: install freshclam list
  command: freshclam

- name: restart clamd
  service:
    name: clamd
    state: restarted

- name: restart freshclam
  service:
    name: freshclam
    state: restarted

- name: reload rspamd
  service:
    name: rspamd
    state: reloaded
