---
- name: generate nsd config
  template:
    src: nsd.conf.j2
    dest: /var/nsd/etc/nsd.conf
    owner: root
    group: _nsd
    mode: '0640'
  notify: restart nsd

- name: enable nsd
  service:
    name: nsd
    enabled: true
    state: started

- name: flush_handlers
  meta: flush_handlers
