---
- name: generate knot config
  template:
    src: knot.conf.j2
    dest: /etc/knot/knot.conf
    owner: root
    group: wheel
    mode: '0640'
  notify: restart knot

- name: enable knot
  service:
    name: knot
    enabled: true
    state: started

- name: flush_handlers
  meta: flush_handlers
