#!/bin/sh

. /usr/local/lib/excision/helpers/variables

# create a public key-pair for dkim for each domain
# and also for davical for each domain

while read -r domain ; do
	for selector in excision dav; do

#		key_ed="$dkim_home/private/${selector}ED.$domain.key"
		key_rsa="$dkim_home/private/${selector}RSA.$domain.key"
#		pub_ed="$dkim_home/${selector}ED.$domain.pub"
		pub_rsa="$dkim_home/${selector}RSA.$domain.pub"
#		txt_ed="$dkim_home/${selector}ED.$domain.txt"
		txt_rsa="$dkim_home/${selector}RSA.$domain.txt"

		printf "### Generating/Checking DKIM certificates for domain: %s\n" "$domain"

		if [ ! -e "$key_rsa" ]; then 
			openssl genrsa -out "$key_rsa" 2048
		fi

#		if [ ! -e "$key_ed"]; then
#			openssl genpkey -algorithm ed25519 -outform PEM -out "$key_ed"
#		fi

		openssl rsa -in "$key_rsa" -pubout -out "$pub_rsa"
#		openssl pkey -in "$key_ed" -pubout -out "$pub_ed"

		printf "\n\n### Creating txt record file from public key\n"

		if [ "$selector" = "excision" ]; then
			rsa_begin="${selector}RSA._domainkey	IN	TXT	"
#			ed_begin="${selector}ED._domainkey	IN	TXT	"
			xtest="v=DKIM1;k=rsa;p="
		else
			rsa_begin="${selector}RSA._domainkey.dav	IN	TXT	"
#			ed_begin="${selector}ED._domainkey.dav	IN	TXT	"
			xtest="k=rsa;t=s;p="
		fi


		pkey_rsa=$(awk 'NR>2 {print last} {last=$0}' ORS='' "$pub_rsa")
#		pkey_ed=$(awk 'NR>2 {print last} {last=$0}' ORS='' "$pub_ed")

		rsa_end=$(echo "$xtest$pkey_rsa;" | awk 'BEGIN {ORS=" "}{for (i=1;i<=length($0);i+=255) printf "\042%s\042 ",substr( $0, i, 255 ) } ')
#		ed_end=$(echo "$xtest$pkey_ed;" | awk 'BEGIN {ORS=" "}{for (i=1;i<=length($0);i+=255) printf "\042%s\042 ",substr( $0, i, 255 ) } ')

		printf "%s\t( %s)\n" "$rsa_begin" "$rsa_end" | tee "$txt_rsa"
#		printf "%s\t( %s\n" "$ed_begin" "$ed_end" | tee "$txt_ed"


		printf "\n\n### Ensuring correct permissions on all three files\n"
#		sh "$vfix" root _rspamd 640 "$key_ed"
		sh "$vfix" root _rspamd 640 "$key_rsa"
#		sh "$vfix" root wheel 644 "$pub_ed"
		sh "$vfix" root wheel 644 "$pub_rsa"
#		sh "$vfix" root wheel 644 "$txt_ed"
		sh "$vfix" root wheel 644 "$txt_rsa"

	done
done < "/etc/mail/vdomains"

rcctl reload rspamd
