#!/bin/sh

. /usr/local/lib/excision/helpers/variables

domain=$(head -n 1 /etc/mail/vdomains)
hostname=$(head -n 1 "$nsd_home/hostname")

echo "### Renewing acme certificates"
acme-client -v -f "$ssl_home/acme-client.conf" "$hostname"
ocspcheck -N -o "$ssl_home/$domain.ocsp" "$ssl_home/$domain.crt"

if [ $? -eq 0 ]; then
	printf "\n### Reloading services"
	rcctl reload httpd dovecot
	rcctl restart smtpd spamd
fi

