#!/bin/sh

printf "\n### SMTPD statistics\n"
smtpctl show stats

printf "\n### Rspamd statistics\n"
/usr/local/bin/rspamc stat

printf "\n### Dovecot statistics\n"
/usr/local/bin/doveadm -f pager quota get -A | tr -d '\f'
