#!/bin/sh

# Checks the consistency of user database and password database

. /usr/local/lib/excision/helpers/variables

virtuals="$user_home/virtual"
revirt="$user_home/revirt"
allowed="$user_home/spamd.alloweddomains"
bak=$(date +%Y%d%m%H%M)

if [ -e "$virtuals" ]; then
	mv "$virtuals" "$virtuals.$bak"
fi
if [ -e "$revirt" ]; then
	mv "$revirt" "$revirt.$bak"
fi
if [ -e "$allowed" ]; then
	mv "$allowed" "$allowed.$bak"
fi

touch "$virtuals" "$revirt" "$allowed"

while read -r domain; do
	printf '@%s\n' "$domain" >> "$allowed"
done < /etc/mail/vdomains

for user_file in "$user_home/user-data/"*; do
	username=$( basename "$user_file" )
	printf "\n%s\t\t\t\texcision" "$username" >> "$virtuals"
	printf "\n%s\t\t\t\t%s" "$username" "$username" >> "$revirt"
	while IFS= read -r alias; do
		printf "\n%s\t\t\t\t%s" "$alias" "$username" >> "$virtuals"
		printf ",%s" "$alias" >> $revirt
	done < "$user_home/user-data/$username"
	printf "\n" >> "$revirt"
done

cp "$virtuals" /etc/mail/virtual
cp "$revirt" /etc/mail/revirt
cp "$allowed" /etc/mail/spamd.alloweddomains
chmod 640 /etc/mail/virtual /etc/mail/revirt /etc/mail/spamd.alloweddomains
chown root:_smtpd /etc/mail/virtual /etc/mail/revirt /etc/mail/spamd.alloweddomains
cp "$user_home/passwd" /etc/mail/passwd
chmod 440 /etc/mail/passwd
chown _smtpd:_dovecot /etc/mail/passwd

# Reload information for services
#supposedly dovecot automatically reloads the changes
#but lets not trust anything
rcctl reload dovecot
smtpctl update table passwd
smtpctl update table virtuals
smtpctl update table revirt 

