#!/bin/sh

. /usr/local/lib/excision/helpers/variables

if [ "$#" -eq 0 ]; then
	echo "Error: no friend ip specified"
	exit 255
fi

ip="$1"
nospamd="$spam_home/nospamd"

touch "$nospamd"

if grep -q "$ip" "$nospamd"; then
	echo "$ip is already bypassing spamd"
	exit 1
else
	echo "$ip" >> "$nospamd"
	pfctl -t nospamd -T replace -f "$nospamd"
fi

