---
- name: add _rspamd to _redis group
  user:
    name: _rspamd
    groups: _redis
    append: true
    create_home: false

- name: create rspamd local.d directory
  file:
    path: /etc/rspamd/local.d/
    state: directory
    owner: root
    group: wheel
    mode: '0755'

- name: create rspamd local configs
  copy:
    src: etc_rspamd_locald/
    dest: /etc/rspamd/local.d/
    force: true
    owner: root
    group: wheel
    mode: '0644'
  notify: restart rspamd

- name: generate rspamd local configs from templates
  template:
    src: "{{ item.name }}"
    dest: "/etc/rspamd/local.d/{{ item.name | replace('.j2', '') }}"
    owner: root
    group: wheel
    mode: '0644'
  with_items: "{{ rspamd_templates }}"
  notify: restart rspamd

- name: enable rspamd
  service:
    name: rspamd
    enabled: true
    state: started

- name: flush_handlers
  meta: flush_handlers
