#!/bin/sh

# Output: 0 -> Doesn't exist
#         1 -> Exists
#         2 -> Exists as alias for another user  

. /usr/local/lib/ansimail/helpers/variables

username="$1"

if [ -e "$user_home/user-data/$username" ]; then
	echo 1
 	exit 0;
fi

for user in "$user_home/user-data/"*; do
	[ -e "$user" ] || break
	if grep -q "$username" "$user"; then
		echo 2
		exit 0
	fi
done

echo 0

