#!/bin/sh

# Output: 0 -> Valid username
#         1 -> Invalid username

#. /usr/local/lib/ansimail/helpers/variables

username="$1"
set -- $(echo $username | sed -e "s/@/ /g")

if [ $# -gt 2 ]; then
	echo "1"
	exit 1
elif grep -q "^$2$" "/etc/mail/vdomains"; then
	echo 0
	exit 0
else
	echo 1
	exit 2
fi
