#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "This can only be run by root"
	exit 1
fi

owner="$1"
group="$2"
mode="$3"
mfile="$4"

old_stat=$(stat -f '%u %g %OLp' "$mfile")
new_stat="$(id -u "$owner") $(getent group "$group" | cut -d: -f3) $mode"

if [ "$old_stat" != "$new_stat" ]; then
	chown "$owner":"$group" "$mfile"
	chmod "$mode" "$mfile"
	echo "Fixed permissions for $4:\t\t$old_stat --> $new_stat"
fi
