#!/bin/sh

if [ "$#" -lt 4 ]; then
	echo "Error: incorrect number of arguments"
	echo "     verbose-fix owner group mode file1 [ file2 file3 ... ]"
	exit 255
fi

owner="$1"
group="$2"
mode="$3"
mfile="$4"

old_stat=$(stat -f '%u %g %OLp' "$mfile")
new_stat="$(id -u "$owner") $(getent group "$group" | cut -d: -f3) $mode"

if [ "$old_stat" != "$new_stat" ]; then
	chown "$owner":"$group" "$mfile"
	chmod "$mode" "$mfile"
	echo "Fixed permissions for $4:\t\t$old_stat --> $new_stat"
fi
