---
- name: generate zone main files
  template:
    src: domain.zone.j2
    dest: "/etc/excision/nsd/{{ item.name }}.zone"
    mode: '0644'
    owner: root
    group: wheel
  with_items: "{{ domains }}"

- name: generate dkim certificates   # noqa no-changed-when
  command: excision ensure-dkim

- name: generate zone final files   # noqa no-changed-when
  command: excision ensure-zone "{{ item.name }}" 0
  with_items: "{{ domains }}"
