---
- name: create excision config directories
  file:
    name: "{{ item.name }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ item.perm }}"
    modification_time: preserve
    access_time: preserve
  with_items: "{{ base_config_dirs }}"

- name: generate mta-sts.txt file
  template:
    src: mta-sts.txt.j2
    dest: /var/www/mta-sts/mta-sts.txt
    owner: root
    group: wheel
    mode: '0644'

- name: create mozilla config directories
  file:
    path: '/var/www/mail/{{ item.name }}/'
    state: directory
    owner: root
    group: wheel
    mode: '0755'

# https://wiki.mozilla.org/Thunderbird:Autoconfiguration#Implementation
- name: generate mozilla config files
  template:
    src: config-v1.1.xml.j2
    dest: "/var/www/mail/{{ item.name }}/config-v1.1.xml"
    owner: root
    group: wheel
    mode: '0644'
  with_items: "{{ domains }}"

- name: create autodiscover directories
  file:
    path: '/var/www/Autodiscover/{{ item.name }}/'
    state: directory
    owner: root
    group: wheel
    mode: '0755'

# https://github.com/gronke/email-autodiscover/blob/master/mail/autodiscover.xml
# https://docs.microsoft.com/en-us/previous-versions/office/office-2010/cc511507(v=office.14)?redirectedfrom=MSDN#Anchor_3
- name: generate autodiscover config files
  template:
    src: Autodiscover.xml.j2
    dest: "/var/www/Autodiscover/{{ item.name }}/Autodiscover.xml"
    owner: root
    group: wheel
    mode: '0644'
  with_items: "{{ domains }}"

- name: create hostname file
  copy:
    content: |
      {{ hostname }}
    dest: /etc/myname
    mode: '0644'
    owner: root
    group: wheel
  notify: set hostname

- name: create mail_subdomain file
  copy:
    content: |
      {{ mail_subdomain }}
    dest: /etc/excision/nsd/mail_subdomain
    mode: '0644'
    owner: root
    group: wheel

- name: create mailname file
  copy:
    content: |
      {{ hostname }}
    dest: /etc/mail/mailname
    mode: '0644'
    owner: root
    group: wheel

- name: create vdomains file
  template:
    src: vdomains.j2
    dest: /etc/mail/vdomains
    mode: '0644'
    owner: root
    group: wheel

- name: ensure passwd file exists
  file:
    path: /etc/excision/users/passwd
    state: touch
    owner: root
    group: wheel
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: generate login.conf
  copy:
    src: login.conf
    dest: /etc/login.conf
    force: true
    owner: root
    group: wheel
    mode: '0644'
  notify: rebuild login database

- name: add daily-report cron job
  cron:
    name: Excision daily-report
    job: "/usr/local/bin/excision daily-report"
    user: root
    hour: "7"
    minute: "30"
