---
- name: create hostname file
  copy:
    content: |
      {{ hostname }}
    dest: /etc/myname
    mode: '0644'
    owner: root
    group: wheel
    modification_time: preserve
    access_time: preserve
  notify: set hostname

- name: create mail_subdomain file
  copy:
    content: |
      {{ mail_subdomain }}
    dest: /etc/excision/nsd/mail_subdomain
    mode: '0644'
    owner: root
    group: wheel
    modification_time: preserve
    access_time: preserve

- name: create mailname file
  copy:
    content: |
      {{ hostname }}
    dest: /etc/mail/mailname
    mode: '0644'
    owner: root
    group: wheel
    modification_time: preserve
    access_time: preserve

- name: create vdomains file
  template:
    src: vdomains.j2
    dest: /etc/mail/vdomains
    mode: '0644'
    owner: root
    group: wheel

- name: create excision config directories
  file:
    name: "{{ item.name }}"
    state: directory
    owner: root
    group: wheel
    mode: "{{ item.perm }}"
    modification_time: preserve
    access_time: preserve
  with_items: "{{ base_config_dirs }}"

- name: ensure passwd file exists
  file:
    path: /etc/excision/users/passwd
    state: touch
    owner: root
    group: wheel
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: generate login.conf
  copy:
    src: login.conf
    dest: /etc/login.conf
    force: true
    owner: root
    group: wheel
    mode: '0644'
    modification_time: preserve
    access_time: preserve
  notify: rebuild login database

- name: add daily-report cron job
  cron:
    name: Excision daily-report
    job: "/usr/local/bin/excision daily-report"
    user: root
    hour: "7"
    minute: "30"
