---
- name: include packages
  import_tasks: packages.yml

- name: include services
  import_tasks: services.yml

- name: include users
  import_tasks: users.yml

- name: include scripts
  import_tasks: scripts.yml

- name: include configs
  import_tasks: configs.yml

- name: flush_handlers
  meta: flush_handlers
