---
- name: make excision group
  group:
    name: excision

- name: make excision user
  user:
    name: excision
    comment: Excision Mail executor
    group: excision
    groups: ""
    login_class: daemon
    shell: /bin/ksh
    home: /var/excision-home
    password_lock: true
    password: "*************"

- name: disable logins for excision user
  file:
    state: absent
    path: /var/excision-home/.ssh/
