---
- name: restart postgresql
  service:
    name: postgresql
    enabled: true
    state: restarted

- name: sysctl semmni
  command: sysctl kern.seminfo.semmni={{ psql_semmni }}

- name: sysctl semmns
  command: sysctl kern.seminfo.semmns={{ psql_semmns }}
