---
- name: restart postgresql
  service:
    name: postgresql
    enabled: true
    state: restarted

- name: sysctl semmni
  command: sysctl kern.seminfo.semmni=90

- name: sysctl semmns
  command: sysctl kern.seminfo.semmns=2048
